import 'package:flutter/material.dart';

final List<String> categories = [
  'Semua',
  'Ekonomi',
  'MPV',
  'SUV',
  'Sedan',
  'Mewah',
  'Van',
  'Motor',
];

final List<Map<String, dynamic>> vehicles = [
  {
    'name': 'Daihatsu Ayla',
    'category': 'Ekonomi',
    'description': 'Mobil city car yang sangat irit BBM dan mudah diparkir, pas untuk keperluan harian di dalam kota.',
    'transmission': 'Manual',
    'price': 250000,
    'seats': 5,
    'likes': 14,
    'isLiked': false,
    'icon': Icons.directions_car_filled,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Agya',
    'category': 'Ekonomi',
    'description': 'Hatchback irit dengan transmisi matic yang nyaman dipakai di jalanan macet.',
    'transmission': 'Matic',
    'price': 275000,
    'seats': 5,
    'likes': 21,
    'isLiked': false,
    'icon': Icons.directions_car_filled,
    'imageUrl': '',
  },
  {
    'name': 'Honda Brio RS',
    'category': 'Ekonomi',
    'description': 'Hatchback lincah dengan tampilan sporty, tenaga responsif dan konsumsi BBM hemat.',
    'transmission': 'Matic',
    'price': 325000,
    'seats': 5,
    'likes': 33,
    'isLiked': false,
    'icon': Icons.directions_car_filled,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Avanza',
    'category': 'MPV',
    'description': 'MPV keluarga favorit di Indonesia. Kabin lega, perawatan mudah, cocok untuk dalam maupun luar kota.',
    'transmission': 'Manual',
    'price': 375000,
    'seats': 7,
    'likes': 48,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Daihatsu Xenia',
    'category': 'MPV',
    'description': 'MPV 7 penumpang dengan transmisi matic, nyaman untuk keluarga dan perjalanan wisata.',
    'transmission': 'Matic',
    'price': 375000,
    'seats': 7,
    'likes': 27,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Suzuki Ertiga',
    'category': 'MPV',
    'description': 'MPV dengan suspensi empuk dan konsumsi BBM efisien, nyaman untuk perjalanan jauh.',
    'transmission': 'Manual',
    'price': 400000,
    'seats': 7,
    'likes': 25,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Mitsubishi Xpander',
    'category': 'MPV',
    'description': 'MPV modern dengan ground clearance tinggi dan kabin luas, aman untuk berbagai kondisi jalan.',
    'transmission': 'Matic',
    'price': 475000,
    'seats': 7,
    'likes': 52,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Innova Reborn',
    'category': 'MPV',
    'description': 'MPV premium yang terkenal tangguh dan nyaman, pilihan utama untuk perjalanan keluarga atau kantor.',
    'transmission': 'Matic',
    'price': 650000,
    'seats': 7,
    'likes': 61,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Daihatsu Terios',
    'category': 'SUV',
    'description': 'SUV kompak yang tangguh dan irit, cocok untuk jalan kota maupun jalan rusak ringan.',
    'transmission': 'Manual',
    'price': 450000,
    'seats': 7,
    'likes': 17,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Rush',
    'category': 'SUV',
    'description': 'SUV 7 penumpang dengan tampilan gagah, nyaman untuk liburan keluarga.',
    'transmission': 'Matic',
    'price': 500000,
    'seats': 7,
    'likes': 29,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Honda HR-V',
    'category': 'SUV',
    'description': 'SUV crossover stylish dengan kabin senyap dan fitur lengkap untuk perjalanan nyaman.',
    'transmission': 'Matic',
    'price': 650000,
    'seats': 5,
    'likes': 35,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Fortuner',
    'category': 'SUV',
    'description': 'SUV besar bertenaga diesel, tangguh untuk perjalanan jauh dan medan yang beragam.',
    'transmission': 'Matic',
    'price': 1000000,
    'seats': 7,
    'likes': 44,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Mitsubishi Pajero Sport',
    'category': 'SUV',
    'description': 'SUV diesel premium dengan performa kuat dan kabin mewah untuk perjalanan jauh.',
    'transmission': 'Matic',
    'price': 1100000,
    'seats': 7,
    'likes': 38,
    'isLiked': false,
    'icon': Icons.directions_car,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Vios',
    'category': 'Sedan',
    'description': 'Sedan ringkas yang nyaman dan irit, sering dipakai untuk keperluan bisnis dan acara resmi.',
    'transmission': 'Matic',
    'price': 500000,
    'seats': 5,
    'likes': 16,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Camry',
    'category': 'Sedan',
    'description': 'Sedan eksekutif dengan kabin luas dan halus, cocok untuk tamu penting dan perjalanan dinas.',
    'transmission': 'Matic',
    'price': 1400000,
    'seats': 5,
    'likes': 23,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Vellfire',
    'category': 'Mewah',
    'description': 'MPV mewah dengan captain seat empuk dan pintu geser elektrik, nyaman untuk tamu VIP.',
    'transmission': 'Matic',
    'price': 1800000,
    'seats': 7,
    'likes': 40,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Alphard',
    'category': 'Mewah',
    'description': 'MPV premium dengan kabin super lega dan fitur lengkap, favorit untuk tamu VIP dan acara spesial.',
    'transmission': 'Matic',
    'price': 2000000,
    'seats': 7,
    'likes': 57,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'BMW 520i',
    'category': 'Mewah',
    'description': 'Sedan mewah sporty dengan performa halus, cocok untuk acara pernikahan dan perjalanan bisnis.',
    'transmission': 'Matic',
    'price': 2500000,
    'seats': 5,
    'likes': 31,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'Mercedes-Benz E-Class',
    'category': 'Mewah',
    'description': 'Sedan mewah dengan kenyamanan kelas atas, pilihan untuk acara istimewa dan tamu kehormatan.',
    'transmission': 'Matic',
    'price': 2500000,
    'seats': 5,
    'likes': 36,
    'isLiked': false,
    'icon': Icons.local_taxi,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Hiace Commuter',
    'category': 'Van',
    'description': 'Minibus 15 kursi yang lega untuk rombongan, wisata, atau acara keluarga besar.',
    'transmission': 'Manual',
    'price': 1000000,
    'seats': 15,
    'likes': 19,
    'isLiked': false,
    'icon': Icons.airport_shuttle,
    'imageUrl': '',
  },
  {
    'name': 'Toyota Hiace Premio',
    'category': 'Van',
    'description': 'Van premium dengan kursi empuk dan AC dingin, nyaman untuk rombongan dan tamu perusahaan.',
    'transmission': 'Matic',
    'price': 1400000,
    'seats': 14,
    'likes': 26,
    'isLiked': false,
    'icon': Icons.airport_shuttle,
    'imageUrl': '',
  },
  {
    'name': 'Isuzu Elf Long',
    'category': 'Van',
    'description': 'Microbus 19 kursi untuk rombongan besar seperti wisata, study tour, dan acara kantor.',
    'transmission': 'Manual',
    'price': 1100000,
    'seats': 19,
    'likes': 12,
    'isLiked': false,
    'icon': Icons.airport_shuttle,
    'imageUrl': '',
  },
  {
    'name': 'Honda Beat',
    'category': 'Motor',
    'description': 'Motor matic ringan dan super irit, mudah dikendarai untuk keliling kota.',
    'transmission': 'Matic',
    'price': 75000,
    'seats': 2,
    'likes': 28,
    'isLiked': false,
    'icon': Icons.two_wheeler,
    'imageUrl': '',
  },
  {
    'name': 'Honda Scoopy',
    'category': 'Motor',
    'description': 'Motor matic bergaya retro dengan jok rendah, nyaman dan mudah dikendalikan.',
    'transmission': 'Matic',
    'price': 85000,
    'seats': 2,
    'likes': 32,
    'isLiked': false,
    'icon': Icons.two_wheeler,
    'imageUrl': '',
  },
  {
    'name': 'Honda Vario 160',
    'category': 'Motor',
    'description': 'Motor matic bertenaga dengan mesin 160cc, nyaman untuk harian maupun jarak menengah.',
    'transmission': 'Matic',
    'price': 100000,
    'seats': 2,
    'likes': 41,
    'isLiked': false,
    'icon': Icons.two_wheeler,
    'imageUrl': '',
  },
  {
    'name': 'Yamaha Aerox 155',
    'category': 'Motor',
    'description': 'Motor matic sporty dengan tenaga responsif dan tampilan agresif.',
    'transmission': 'Matic',
    'price': 125000,
    'seats': 2,
    'likes': 24,
    'isLiked': false,
    'icon': Icons.electric_moped,
    'imageUrl': '',
  },
  {
    'name': 'Yamaha NMAX',
    'category': 'Motor',
    'description': 'Motor matic premium dengan jok luas dan suspensi empuk, nyaman untuk perjalanan jauh.',
    'transmission': 'Matic',
    'price': 150000,
    'seats': 2,
    'likes': 55,
    'isLiked': false,
    'icon': Icons.electric_moped,
    'imageUrl': '',
  },
  {
    'name': 'Honda PCX 160',
    'category': 'Motor',
    'description': 'Motor matic premium yang halus dan stabil, cocok untuk perjalanan jarak jauh.',
    'transmission': 'Matic',
    'price': 150000,
    'seats': 2,
    'likes': 37,
    'isLiked': false,
    'icon': Icons.electric_moped,
    'imageUrl': '',
  },
  {
    'name': 'Honda CRF150L',
    'category': 'Motor',
    'description': 'Motor trail bertransmisi manual, tangguh untuk jalan rusak, pegunungan, dan petualangan.',
    'transmission': 'Manual',
    'price': 250000,
    'seats': 2,
    'likes': 18,
    'isLiked': false,
    'icon': Icons.two_wheeler,
    'imageUrl': '',
  },
  {
    'name': 'Vespa Primavera',
    'category': 'Motor',
    'description': 'Skuter klasik Italia bergaya elegan, favorit untuk berkeliling kota dan foto-foto.',
    'transmission': 'Matic',
    'price': 250000,
    'seats': 2,
    'likes': 46,
    'isLiked': false,
    'icon': Icons.electric_moped,
    'imageUrl': '',
  },
];

final List<Map<String, dynamic>> cart = [];

const int driverFee = 150000;
const int insuranceFee = 50000;

int cartTotal() {
  return cart.fold(0, (sum, item) => sum + (item['total'] as int));
}

String formatRupiah(int number) {
  return number.toString().replaceAllMapped(
    RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
        (Match m) => '${m[1]}.',
  );
}

String formatTanggal(DateTime d) {
  return '${d.day}/${d.month}/${d.year}';
}

Widget vehicleImage(Map<String, dynamic> vehicle, double size) {
  Widget iconBox = Container(
    width: size,
    height: size,
    color: const Color(0xFF161616),
    child: Icon(vehicle['icon'], size: size / 2, color: const Color(0xFFD4D4D4)),
  );

  if (vehicle['imageUrl'] == '') {
    return iconBox;
  }

  return Image.network(
    vehicle['imageUrl'],
    width: size,
    height: size,
    fit: BoxFit.cover,
    errorBuilder: (context, error, stackTrace) => iconBox,
  );
}